author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/getEncryption'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 1
      #school 学校全称
      schoolName: 安康学院
      #username 学号或者工号
      username: '2024020090'
      #password 密码
      password: 'skj60302'
      # 地址信息
      address: '安康市汉滨区'
      # sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 104.616858
      #lat 纬度
      lat: 28.793022
      # 检查标题与否
      checkTitle: 1
      # 代理ip信息（若无可忽略本设置、该配置仅供您所在环境ip被ban且自己拥有代理ip使用）（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy: ''
      # isOffset 坐标偏移开关，默认打开坐标偏移开关，若一直出现不在签到范围且确保自己填写的lon和lat在坐标范围内，请尝试关闭本功能
      isOffset: true
      # 表单信息
      forms:
        - form:
            title: 2.是否在校上班或居住
            value: 是
        - form:
            title: 3.上午体温
            value: 36.2
        - form:
            title: 4.下午体温
            value: 36.4
        - form:
            title: 5.晚上体温
            value: 36.1
        - form:
            title: 6.身体状况
            value: 身体健康
        - form:
            title: 7.是否请假
            value: 否
        - form:
            title: 8.今日是否返回宜宾市
            value: 否
