name: Attendance
on:
  workflow_dispatch:
  schedule:
    - cron: 45 22 * * *
env:
  TZ: Asia/Shanghai
jobs:
  Auto-Attendance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install & Run
      run: |
        git clone https://gitlab.com/Boos4721/fucktodaystudy.git --depth=1 fuckTodayStudy
        sed -i 's/tencentcloud_sdk_python==3.0.65/tencentcloud_sdk_python/; s/PyYAML==5.4.1/PyYAML/' fuckTodayStudy/requirements.txt
        pip install -r fuckTodayStudy/requirements.txt
        mv config.yml fuckTodayStudy/config.yml
        mv system.yml fuckTodayStudy/login/system.yml 2>/dev/null || true
        mv sign.jpg fuckTodayStudy/sign.jpg 2>/dev/null || true
        cd fuckTodayStudy && python index.py

